# Generated by Django 2.2.14 on 2021-09-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
