# Generated by Django 2.2.14 on 2021-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
