# Generated by Django 2.2.14 on 2021-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='bair',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='district',
            new_name='code',
        ),
        migrations.AddField(
            model_name='address',
            name='davhar',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='duureg',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='khoroo_khotkhon',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='nemelt',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='orts',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='toot',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
