# Generated by Django 3.2.4 on 2021-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
