# Generated by Django 2.2.14 on 2021-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210906_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.BooleanField(default=False),
        ),
    ]
