# Generated by Django 2.2.14 on 2021-09-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
