# Generated by Django 2.2.14 on 2021-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210627_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Цэвэрлэгч'), ('S', 'Тонер'), ('S', 'Нарны тос'), ('S', 'Хөгшрөлтийн эсрэг'), ('S', 'Гуужуулагч'), ('S', 'Эссэнц'), ('S', 'Серум'), ('S', 'Үс арчилгаа'), ('OW', 'Бие арчилгаа'), ('S', 'Маск'), ('S', 'Нүүрний будаг'), ('S', 'Зовхины тос')], max_length=2),
        ),
    ]
