# Generated by Django 2.2.14 on 2021-10-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210926_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
    ]
