# Generated by Django 2.2.14 on 2021-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.IntegerField(unique=True),
        ),
    ]
