# Generated by Django 2.2.14 on 2021-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210628_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'Цэвэрлэгч'), ('TO', 'Тонер'), ('NT', 'Нарны тос'), ('HE', 'Хөгшрөлтийн эсрэг'), ('GU', 'Гуужуулагч'), ('ES', 'Эссэнц'), ('SE', 'Серум'), ('UA', 'Үс арчилгаа'), ('BA', 'Бие арчилгаа'), ('MA', 'Маск'), ('NB', 'Нүүрний будаг'), ('ZT', 'Зовхины тос')], max_length=2),
        ),
    ]
